<?php
	$script = $argv[0];
	$vesion = phpversion();;
	echo "Status: 200\r\n";
	echo "Content-Type: text/plain\r\n\r\n";
?>
<html>
	<head>
		<title>python CGI</title>
	</head>
	<body>
		<p>
			this page is generated by php CGI<br>
			php version: <?php echo $vesion ?><br>
			script name: <?php echo $script ?><br>
			server name: Ed Edd n Eddy/1.0<br>
		</p>
	</body>
</html>
