<?php
	// header
	echo "Status: 200\r\n";
	echo "Content-Type: text/plain\r\n\r\n";
	// body
	echo "<--This output is generated by a php script-->\n\n";
	echo "Neque porro quisquam est qui dolorem ipsum quia\ndolor sit amet, consectetur, adipisci velit...\n";
	echo "There is no one who loves pain itself, who seeks\nafter it and wants to have it, simply because\n it is pain...\n";
?>