from sys import version, argv
from os import environ

if "SERVER_SOFTWARE" not in environ:
	environ["SERVER_SOFTWARE"] = "Ed Edd n Eddy/1.0"

CRLF='\r\f'
current_version = version
script_name = argv[0]

print("Content-Type: text/html", end=CRLF)
print("Status: 200", end=CRLF)
print(CRLF, end='')
print(
f"""<html>
	<head>
		<title>python CGI</title>
	</head>
	<body>
		<p>
			this page is generated by python CGI <br>
			python version: {current_version}<br>
			script name: {script_name}<br>
			server name: {environ['SERVER_SOFTWARE']}<br>
		</p>
	</body>
</html>\n""")