#!/bin/bash
version=$(bash --version | head -n 1)
script_name="$0"

echo -en "Content-Type: text/html\r\n"
echo -en "Status: 200\r\n\r\n"

echo -en "<html>
	<head>
		<title>bash CGI</title>
	</head>
	<body>
		<p>
			this page is generated by bash CGI <br>
			bash version: $version<br>
			script name: $script_name<br>
			server name: Ed Edd n Eddy/1.0<br>
		</p>
	</body>
</html>\n"